[project]
<<<<<<< HEAD
name = "Pythonic_RawCopy"
version = "0.1.0"
description = "Copy file from NTFS image using MFT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ['boto3']

[tool.uv.workspace]
members = [
    "src",
]
=======
name = "mft-based-copy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ['boto3']
>>>>>>> ac75fa3da02f15b54b72eec8b7ee154a2184ac82
