[project]
name = "Pythonic_RawCopy"
version = "0.1.0"
description = "Copy file from NTFS image using MFT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ['boto3']

[tool.uv.workspace]
members = [
    "src",
]
